tabItem(tabName = "summary",
        tabsetPanel(tabPanel(p(id = "element","Variant Peptide Table"),
                             tabsetPanel(tabPanel("Summary", br(),
                                                  box(title = "Variant Peptide Data Summary", br(),hr(),
                                                      textOutput(outputId = "rows"),br(),hr(),
                                                      textOutput(outputId = "pep_num"),br(),hr(),
                                                      textOutput(outputId = "gene_num"),br(),hr(),
                                                      textOutput(outputId = "psm_num"),br(),hr(),
                                                      textOutput(outputId = "snp_num"),br(),hr(),
                                                      width = 6, height = 561,solidHeader = T, status = "primary"),
                                                  box(title = "Intensity Distribution for all Peptides",
                                                      sliderInput("ibins",
                                                                  "Number of bins:",
                                                                  min = 1,
                                                                  max = 100,
                                                                  value = 30),
                                                      plotOutput(outputId = "intensity"), solidHeader = T, status = "primary")
                             ),
                             
                             
                             
                             tabPanel("Distributions and Filtering", br(),
                                      fluidRow(
                                        box(title = "Minimal Intensity Distribution", hr(),
                                            sliderInput("minbins",
                                                        "Number of bins:",
                                                        min = 1,
                                                        max = 100,
                                                        value = 30), br(), hr(),
                                            plotOutput(outputId = "minimal"), hr(),height = 708,solidHeader = T, status = "primary"),
                                        box(title = "Maximal Intensity Distribution", hr(),
                                            sliderInput("maxbins",
                                                        "Number of bins:",
                                                        min = 1,
                                                        max = 100,
                                                        value = 30),br(), hr(),
                                            plotOutput(outputId = "maximal"), hr(),height = 708,solidHeader = T, status = "primary")),
                                      fluidRow(
                                        box(title = "S/N Ratio Distribution", hr(),
                                            sliderInput("sbins",
                                                        "Number of bins:",
                                                        min = 1,
                                                        max = 100,
                                                        value = 30),br(), hr(),
                                            plotOutput(outputId = "sn"), hr(),height = 708,solidHeader = T, status = "primary"),
                                        
                                        
                                        box(title = "Variant Peptide Data Filtering", hr(),
                                            radioButtons(inputId = "minfilter",
                                                         label = "Minimal Intensity Distribution (intensity of reference peptides)",
                                                         choices = c("No Filtering" = "nofilter", 
                                                                     "Input Filter: " = "filter"),
                                                         selected = "filter"),
                                            conditionalPanel(condition = "input.minfilter == 'filter'",
                                                             numericInput(inputId = "minfiltervalue",
                                                                          label = NULL,
                                                                          value = NULL, width = "200px"),
                                                             htmlOutput(outputId = "minrecfilter", inline = T)),
                                            hr(),
                                            
                                            radioButtons(inputId = "maxfilter",
                                                         label = "Maximal Intensity Distribution",
                                                         choices = c("No Filtering" = "nofilter", 
                                                                     "Input Filter: " = "filter"),
                                                         selected = "filter"),
                                            conditionalPanel(condition = "input.maxfilter == 'filter'",
                                                             numericInput(inputId = "maxfiltervalue",
                                                                          label = NULL,
                                                                          value = NULL, width = "200px"),
                                                             htmlOutput(outputId = "maxrecfilter")),
                                            hr(),
                                            
                                            radioButtons(inputId = "snfilter",
                                                         label = "S/N Ratio Distribution",
                                                         choices = c("No Filtering" = "nofilter", 
                                                                     "Input Filter: " = "filter"),
                                                         selected = "filter"),
                                            conditionalPanel(condition = "input.snfilter == 'filter'",
                                                             numericInput(inputId = "snfiltervalue",
                                                                          label = NULL,
                                                                          value = NULL, width = "200px"),
                                                             htmlOutput(outputId = "snrecfilter")),hr(), width = 3, solidHeader = T, status = "primary"),
                                        
                                        box(title = "Filter Summary", hr(),
                                            textOutput(outputId = "minimal.filter"), hr(),
                                            textOutput(outputId = "maximal.filter"),hr(),
                                            textOutput(outputId = "sn.filter"),hr(),
                                            textOutput(outputId = "filt.num"),hr(),
                                            textOutput(outputId = "filt.unique"), hr(), br(),
                                            h4("Save Filtered Output"), hr(),
                                            textInput("pep.filename", "Enter name for download file:", value = "Filtered_Variant_Peptide_Data"),
                                            radioButtons("pep.sep", label = "Separator", choices = c("Comma" = "csv",
                                                                                                     "Tab" = "\t"), selected = "\t"),
                                            downloadButton(outputId = "peptide.download", label = "Download"),
                                            width = 3, height = 708,solidHeader = T, status = "primary")),
                                      fluidRow(
                                        box(title = "Filtered Data Table (First 100 Rows)", 
                                            DT::dataTableOutput(outputId = "filter.table"), 
                                            width = 12, solidHeader = T, status = "primary"))), 
                             
                             
                             
                             tabPanel("Sample Cluster", br(),
                                      box(title = "PCA Plot", br(),
                                          plotOutput(outputId = "pca"), br(),solidHeader = T, status = "primary")))),
                    
                    
                    tabPanel(p(id = "element","Genotype Data"),
                             tabsetPanel(tabPanel("Summary", br(),
                                                  box(title = "Genotype Data Summary", br(), hr(),
                                                      textOutput(outputId = "geno.snps") %>% withSpinner(type = 7), br(),hr(),
                                                      textOutput(outputId = "geno.pepsnps"), br(), hr(),
                                                      textOutput(outputId = "geno.missing"), br(), hr(),
                                                      textOutput(outputId = "geno.samples"), br(), hr(),
                                                      textOutput(outputId = "geno.match"), br(), hr(),
                                                      width = 6, height = 562, solidHeader = T, status = "primary"),
                                                  box(title = "Minor Allele Frequency (MAF) Distribution",
                                                      sliderInput("maf.bins",
                                                                  label = "Number of bins:",
                                                                  min = 1, 
                                                                  max = 100,
                                                                  value = 30),
                                                      plotOutput(outputId = "maf.hist") %>% withSpinner(type = 7), width = 6, solidHeader = T, status = "primary")
                             ),
                             tabPanel("Distributions and Filtering", br(),
                                      fluidRow(
                                        box(title = "SNPs with Missing Sample Genotypes",
                                            sliderInput("na.bins",
                                                        label = "Number of bins:",
                                                        min = 1, 
                                                        max = 100,
                                                        value = 30),
                                            plotOutput(outputId = "na.hist"), solidHeader = T, status = "primary"),
                                        box(title = "Genotype Data Filtering", hr(),
                                            radioButtons("filtna", "Filter Out SNPs With Missing Genotype Values",
                                                         choices = c("No Filter" = "nofilter",
                                                                     "Filter" = "filter"),
                                                         selected = "nofilter"),
                                            conditionalPanel(condition = "input.filtna == 'filter'",
                                                             numericInput(inputId = "na.allowed",
                                                                          label = "Number of Missing Genotypes Allowed:",
                                                                          value = 0, width = "200px")), hr(), br(),
                                            radioButtons("filt.overlap", "Filter Out SNPs That DO NOT Appear in Filtered Variant Peptide Table",
                                                         choices = c("No Filter/Input VCF is Already Filtered" = "nofilter",
                                                                     "Filter" = "filter"),
                                                         selected = "nofilter"),
                                            HTML(paste0("<b><i>","**This filter will be applied when SMAP is run, 
                                                                        but can be set here to see/download filtered vcf","</b></i>")),
                                            hr(), width = 3, solidHeader = T, status = "primary"),
                                        box(title = "Filtering summary", hr(),
                                            textOutput(outputId = "filt.snps") %>% withSpinner(type = 7), hr(),
                                            textOutput(outputId = "filt.missing"), hr(), br(),
                                            h4("Save Filtered Output"), hr(),
                                            textInput("vcf.filename", "Enter name for download file:", value = "Filtered_Genotype_Data"),
                                            radioButtons("vcf.sep", label = "Separator", choices = c("Comma" = "csv",
                                                                                                     "Tab" = "\t"), selected = "\t"),
                                            downloadButton(outputId = "vcf.download", label = "Download"), hr(), width = 3,height = 560,solidHeader = T, status = "primary")),
                                      fluidRow(
                                        box(title = "Filtered VCF Preview (First 100 lines)",
                                            DT::dataTableOutput(outputId = "vcf.filt.table") %>% withSpinner(type = 7), 
                                            width = 12, solidHeader = T, status = "primary"))),
                             tabPanel("Allele Frequency", br(),
                                      fluidRow(
                                        box(title = "Reference Allele Frequency of Filtered Genotype Data",
                                            sliderInput("ref.bins", label = "Number of bins:",
                                                        min = 1, 
                                                        max = 100,
                                                        value = 30),
                                            plotOutput(outputId = "ref.hist") %>% withSpinner(type = 7), solidHeader = T, status = "primary"),
                                        box(title = "Alternate Allele Frequency of Filtered Genotype Data",
                                            sliderInput("alt.bins", label = "Number of bins:",
                                                        min = 1, 
                                                        max = 100,
                                                        value = 30),
                                            plotOutput(outputId = "alt.hist") %>% withSpinner(type = 7), solidHeader = T, status = "primary")))))
        )
)